export const ENEMY_TYPES = {
  JELLY: 'jelly',
  DUCK: 'duck',
  PIGGY: 'piggy',
  SAUCER: 'saucer',
  SPOOKY: 'spooky',
  BOSS: 'boss',
};

export const ENEMY_CONFIG = {
  [ENEMY_TYPES.JELLY]: {
    name: '粉红果冻怪',
    hp: 85,
    speed: 80,
    reward: 10,
    damage: 1,
    color: 0xf472b6,
    radius: 10,
    icon: '🍮',
  },
  [ENEMY_TYPES.DUCK]: {
    name: '疾风呆呆鸭',
    hp: 45,
    speed: 150,
    reward: 12,
    damage: 1,
    color: 0xfbbf24,
    radius: 8,
    icon: '⚡',
  },
  [ENEMY_TYPES.PIGGY]: {
    name: '笨笨巨力猪',
    hp: 300,
    speed: 50,
    reward: 25,
    damage: 2,
    armor: 0.3,
    color: 0xa855f7,
    radius: 14,
    icon: '🐷',
  },
  [ENEMY_TYPES.SAUCER]: {
    name: '漂浮飞碟怪',
    hp: 150,
    speed: 75,
    reward: 22,
    damage: 2,
    shield: 100,
    color: 0x38bdf8,
    radius: 11,
    icon: '🛸',
  },
  [ENEMY_TYPES.SPOOKY]: {
    name: '调皮小幽灵',
    hp: 110,
    speed: 95,
    reward: 18,
    damage: 1,
    stealthOnHit: true,
    color: 0x34d399,
    radius: 10,
    icon: '👻',
  },
  [ENEMY_TYPES.BOSS]: {
    name: '巨型大萌王',
    hp: 950,
    speed: 40,
    reward: 100,
    damage: 5,
    armor: 0.2,
    shield: 180,
    color: 0xef4444,
    radius: 18,
    icon: '👑',
  },
};
