export const TOWER_TYPES = {
  BOTTLE: 'bottle',
  POOP: 'poop',
  SUN: 'sun',
  FAN: 'fan',
  MAGIC: 'magic',
  ROCKET: 'rocket',
};

export const TOWER_CONFIG = {
  [TOWER_TYPES.BOTTLE]: {
    name: '瓶子炮',
    icon: '🍼',
    tag: '单体·极速',
    description: '单体高频射击，满级为周围防御塔提供攻速加成',
    color: 0x10b981,
    accentColor: 0x34d399,
    bulletType: 'bottle',
    levels: [
      { damage: 18, range: 130, attackSpeed: 450, buildCost: 20, upgradeCost: 0, sellValue: 12, aura: false },
      { damage: 38, range: 155, attackSpeed: 360, buildCost: 20, upgradeCost: 30, sellValue: 30, aura: false },
      { damage: 72, range: 180, attackSpeed: 280, buildCost: 20, upgradeCost: 65, sellValue: 69, aura: true, auraSpeedBoost: 0.25 },
    ],
  },
  [TOWER_TYPES.POOP]: {
    name: '便便塔',
    icon: '💩',
    tag: '黏液·强力减速',
    description: '投掷黏糊糊的便便泥浆，使目标大幅减速',
    color: 0xb45309,
    accentColor: 0xd97706,
    bulletType: 'poop',
    levels: [
      { damage: 12, range: 120, attackSpeed: 1000, buildCost: 25, upgradeCost: 0, sellValue: 15, slow: 0.45, slowDuration: 2200 },
      { damage: 25, range: 145, attackSpeed: 850, buildCost: 25, upgradeCost: 35, sellValue: 36, slow: 0.6, slowDuration: 2800 },
      { damage: 50, range: 175, attackSpeed: 700, buildCost: 25, upgradeCost: 70, sellValue: 78, slow: 0.75, slowDuration: 3500, splashSlow: true },
    ],
  },
  [TOWER_TYPES.SUN]: {
    name: '太阳花',
    icon: '🌻',
    tag: '360°全方位·清图',
    description: '周期性向四周扩散灼热光波，快速清除大片敌人与障碍物',
    color: 0xf59e0b,
    accentColor: 0xfde047,
    bulletType: 'sun',
    levels: [
      { damage: 32, range: 110, attackSpeed: 1300, buildCost: 45, upgradeCost: 0, sellValue: 27, radialAoE: true },
      { damage: 65, range: 135, attackSpeed: 1100, buildCost: 45, upgradeCost: 55, sellValue: 60, radialAoE: true },
      { damage: 125, range: 165, attackSpeed: 900, buildCost: 45, upgradeCost: 95, sellValue: 117, radialAoE: true },
    ],
  },
  [TOWER_TYPES.FAN]: {
    name: '风扇塔',
    icon: '🪭',
    tag: '穿透·全屏直线',
    description: '发射高速旋转的飞叶风刃，直线贯穿整条道路上的所有敌人',
    color: 0x06b6d4,
    accentColor: 0x67e8f9,
    bulletType: 'fan',
    levels: [
      { damage: 22, range: 135, attackSpeed: 850, buildCost: 35, upgradeCost: 0, sellValue: 21, piercing: true },
      { damage: 48, range: 160, attackSpeed: 720, buildCost: 35, upgradeCost: 45, sellValue: 48, piercing: true },
      { damage: 95, range: 190, attackSpeed: 600, buildCost: 35, upgradeCost: 80, sellValue: 96, piercing: true },
    ],
  },
  [TOWER_TYPES.MAGIC]: {
    name: '魔法球',
    icon: '🔮',
    tag: '多目标·持续电击',
    description: '向多个敌人同时发射魔法光束，持续电击输出',
    color: 0xa855f7,
    accentColor: 0xc084fc,
    bulletType: 'magic',
    levels: [
      { damage: 28, maxTargets: 1, range: 125, attackSpeed: 500, buildCost: 40, upgradeCost: 0, sellValue: 24 },
      { damage: 52, maxTargets: 2, range: 150, attackSpeed: 420, buildCost: 40, upgradeCost: 50, sellValue: 54 },
      { damage: 90, maxTargets: 3, range: 180, attackSpeed: 350, buildCost: 40, upgradeCost: 90, sellValue: 108 },
    ],
  },
  [TOWER_TYPES.ROCKET]: {
    name: '火箭炮',
    icon: '🚀',
    tag: '追踪·超强巨爆',
    description: '发射超远程跟踪火箭，命中发生巨型爆炸造成毁灭伤害',
    color: 0xef4444,
    accentColor: 0xf87171,
    bulletType: 'rocket',
    levels: [
      { damage: 60, splash: 65, range: 140, attackSpeed: 1500, buildCost: 55, upgradeCost: 0, sellValue: 33 },
      { damage: 115, splash: 80, range: 170, attackSpeed: 1300, buildCost: 55, upgradeCost: 70, sellValue: 75 },
      { damage: 210, splash: 100, range: 200, attackSpeed: 1050, buildCost: 55, upgradeCost: 115, sellValue: 144 },
    ],
  },
};
