export const TOWER_TYPES = {
  SWORD: 'sword',
  TURTLE: 'turtle',
  FIRE: 'fire',
  FAN: 'fan',
  THUNDER: 'thunder',
  GODFIRE: 'godfire',
};

export const TOWER_CONFIG = {
  [TOWER_TYPES.SWORD]: {
    name: '飞剑塔',
    icon: '🗡️',
    tag: '御剑·极速',
    description: '施展御剑术高频单体穿刺，满级触发“万剑归宗”提升周围 25% 攻速',
    color: 0x10b981,
    accentColor: 0x34d399,
    bulletType: 'sword',
    levels: [
      { damage: 18, range: 130, attackSpeed: 450, buildCost: 20, upgradeCost: 0, sellValue: 12, aura: false },
      { damage: 38, range: 155, attackSpeed: 360, buildCost: 20, upgradeCost: 30, sellValue: 30, aura: false },
      { damage: 72, range: 180, attackSpeed: 280, buildCost: 20, upgradeCost: 65, sellValue: 69, aura: true, auraSpeedBoost: 0.25 },
    ],
  },
  [TOWER_TYPES.TURTLE]: {
    name: '玄龟塔',
    icon: '🪨',
    tag: '玄水·重力封滞',
    description: '引玄龟镇魔重水形成重力泥沼，大幅迟缓减速魔族妖人',
    color: 0x0284c7,
    accentColor: 0x38bdf8,
    bulletType: 'turtle',
    levels: [
      { damage: 12, range: 120, attackSpeed: 1000, buildCost: 25, upgradeCost: 0, sellValue: 15, slow: 0.45, slowDuration: 2200 },
      { damage: 25, range: 145, attackSpeed: 850, buildCost: 25, upgradeCost: 35, sellValue: 36, slow: 0.6, slowDuration: 2800 },
      { damage: 50, range: 175, attackSpeed: 700, buildCost: 25, upgradeCost: 70, sellValue: 78, slow: 0.75, slowDuration: 3500, splashSlow: true },
    ],
  },
  [TOWER_TYPES.FIRE]: {
    name: '九阳真火塔',
    icon: '☀️',
    tag: '纯阳·360°真火',
    description: '释放纯阳三昧真火环形扩散，持续焚烧成片妖人与清破灵物',
    color: 0xf59e0b,
    accentColor: 0xfde047,
    bulletType: 'fire',
    levels: [
      { damage: 32, range: 110, attackSpeed: 1300, buildCost: 45, upgradeCost: 0, sellValue: 27, radialAoE: true },
      { damage: 65, range: 135, attackSpeed: 1100, buildCost: 45, upgradeCost: 55, sellValue: 60, radialAoE: true },
      { damage: 125, range: 165, attackSpeed: 900, buildCost: 45, upgradeCost: 95, sellValue: 117, radialAoE: true },
    ],
  },
  [TOWER_TYPES.FAN]: {
    name: '乾坤宝扇',
    icon: '🌀',
    tag: '太虚·直线穿透',
    description: '挥舞太虚乾坤扇发射狂风罡刃，直线全屏穿透整条小径上的妖魔',
    color: 0x06b6d4,
    accentColor: 0x67e8f9,
    bulletType: 'fan',
    levels: [
      { damage: 22, range: 135, attackSpeed: 850, buildCost: 35, upgradeCost: 0, sellValue: 21, piercing: true },
      { damage: 48, range: 160, attackSpeed: 720, buildCost: 35, upgradeCost: 45, sellValue: 48, piercing: true },
      { damage: 95, range: 190, attackSpeed: 600, buildCost: 35, upgradeCost: 80, sellValue: 96, piercing: true },
    ],
  },
  [TOWER_TYPES.THUNDER]: {
    name: '紫雷珠',
    icon: '🔮',
    tag: '九天·多重玄雷',
    description: '凝聚九天紫霄神雷，同时锁定并持续电击 1~3 个魔族敌人',
    color: 0xa855f7,
    accentColor: 0xc084fc,
    bulletType: 'thunder',
    levels: [
      { damage: 28, maxTargets: 1, range: 125, attackSpeed: 500, buildCost: 40, upgradeCost: 0, sellValue: 24 },
      { damage: 52, maxTargets: 2, range: 150, attackSpeed: 420, buildCost: 40, upgradeCost: 50, sellValue: 54 },
      { damage: 90, maxTargets: 3, range: 180, attackSpeed: 350, buildCost: 40, upgradeCost: 90, sellValue: 108 },
    ],
  },
  [TOWER_TYPES.GODFIRE]: {
    name: '诛仙天火弩',
    icon: '🚀',
    tag: '诛仙·追踪神雷',
    description: '发射追踪诛仙神火弩矢，命中产生天翻地覆的毁灭范围灵爆',
    color: 0xef4444,
    accentColor: 0xf87171,
    bulletType: 'godfire',
    levels: [
      { damage: 60, splash: 65, range: 140, attackSpeed: 1500, buildCost: 55, upgradeCost: 0, sellValue: 33 },
      { damage: 115, splash: 80, range: 170, attackSpeed: 1300, buildCost: 55, upgradeCost: 70, sellValue: 75 },
      { damage: 210, splash: 100, range: 200, attackSpeed: 1050, buildCost: 55, upgradeCost: 115, sellValue: 144 },
    ],
  },
};
